# Generated by Django 3.0.6 on 2020-05-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
